name: app_environment
channels:
  - snowflake
dependencies:
  - beautifulsoup4=4.12.3
  - biopython=1.78
  - datasets=3.3.2
  - easyocr=1.7.0
  - huggingface_hub=0.29.2
  - langchain-core=0.3.25
  - markdown-it-py=2.2.0
  - numexpr=2.10.1
  - numpy=2.2.2
  - openai=1.60.1
  - openpyxl=3.1.5
  - pandas=2.2.3
  - pdfminer.six=20231228
  - playwright-python=1.50.0
  - pypdf=4.2.0
  - pypdf2=3.0.1
  - python=3.10.*
  - python-dotenv=0.21.0
  - python-pptx=1.0.2
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - snowflake-snowpark-python=
  - streamlit=
  - sympy=1.13.3
  - torchvision=0.18.1
  - tqdm=4.67.1
  - xlrd=2.0.1
